# Generated by Django 6.1 on 2026-08-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Bio', 'Bio'), ('Skill', 'Skill'), ('Project', 'Project'), ('Experience', 'Experience'), ('General', 'General')], default='General', max_length=50)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=120)),
                ('headline', models.CharField(default='AI Engineer / Developer', max_length=200)),
                ('summary', models.TextField(default='I build AI products, robust backend systems, and interactive tools that solve real user problems.')),
                ('location', models.CharField(default='Remote / India', max_length=120)),
                ('email', models.EmailField(default='you@example.com', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com/yourusername')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/yourusername')),
                ('resume_url', models.URLField(blank=True, default='')),
                ('availability', models.CharField(default='Open to AI Engineer roles', max_length=120)),
                ('work_style', models.TextField(default='Product-minded, research-driven, and strong on engineering execution.')),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('impact', models.CharField(blank=True, max_length=200)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('repo_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.CharField(default='AI', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AI', 'AI'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Data', 'Data'), ('Cloud', 'Cloud'), ('Tools', 'Tools')], default='AI', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=80)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
