# Generated by Django 5.1.1 on 2026-08-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentry',
            name='category',
            field=models.CharField(choices=[('Bio', 'Bio'), ('Skill', 'Skill'), ('Project', 'Project'), ('Experience', 'Experience'), ('Achievement', 'Achievement'), ('Education', 'Education'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
